spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Ruifeng-Wu/SpringCloudConfig
          search-paths: test
          username:
          password:
server:
  port: 8878
client:
  serviceUrl:
    defaultZone: http://localhost:8888/eureka/
